spring.application.name=bookapp
spring.datasource.url=jdbc:mysql://localhost:3306/bookapp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=7695

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

server.port=8080

app.jwt.secret=school-bookapp-secret-key-min-32-chars-long
app.jwt.expiration-ms=86400000